<a href="https://colab.research.google.com/github/zw2788/LocalMinimaConstruction/blob/main/LocalMinimaEx1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from typing import Tuple

import numpy as np
import pandas as pd

from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from IPython.display import Image

In [3]:
data = pd.read_csv(
    "https://raw.githubusercontent.com/zw2788/LocalMinimaConstruction/main/Ex1.csv")

data.head()

x_2dvec  y
0    [2.8,0.4]  1
1    [3.1,4.3]  1
2   [0.1,-3.4]  1
3  [-4.2,-3.3]  1
4   [-0.5,0.2]  1

In [6]:
features = [
    "x_2dvec",

]
label = "y"

# train test split
X_raw,  Y = data[features].values, data[label].values

#convert string to array
X_raw = np.array([eval(s[0]) for s in X_raw])

# Standardize the input
# Leave blank to match the example in paper

# formatting
Y = Y.reshape((-1, 1))
print(X_raw)
print(Y)
print(X_raw.shape[0])

[[ 2.8  0.4]
 [ 3.1  4.3]
 [ 0.1 -3.4]
 [-4.2 -3.3]
 [-0.5  0.2]
 [-2.7 -0.4]
 [-3.  -4.3]
 [-0.1  3.4]
 [ 4.2  3.2]
 [ 0.4 -0.1]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
10


Neural Structure:
$M((x_0, x_1)) = \sigma(v_0σ(w_{0,0}x_0 + w_{0,1}x_1 + b_0) + v_1σ(w_{1,0}x_0 + w_{1,1}x_1 + b_1) + c) $

In [7]:
Image(url='https://github.com/zw2788/LocalMinimaConstruction/blob/main/221Sigmoid.png?raw=true')


In [21]:
def sigmoid(x):
    """Calculates sigmoid function."""
    return 1. / (1 + np.exp(-x))

# parameters between input layer and the hidden layer
W_0 = np.random.normal(size=(2, X_raw.shape[1]))
print(f"Shape of W_0 is {W_0.shape}")
print(W_0)
print(W_0.shape[1])
b = np.random.normal(size=(2, 1))
print(f"Shape of b_1 is {b.shape}")

# parameters between hidden layer and output layer
V_0 = np.random.normal(size=(1, W_0.shape[1]))
c = np.random.normal(size=(1, 1))

# calculate the forward propagation
Z_1 = X_raw @ W_0.T
print(f"\nShape of Z_1 is {Z_1.shape}")
print("Samples for Z_1:")
print(Z_1[:5])

A_1 = sigmoid(Z_1 + b.T)
print(f"Shape of A_1 is {A_1.shape}")
print("Samples for A_1:")
print(A_1[:5])

Z_2 = A_1 @ V_0.T
print(f"\nShape of Z_2 is {Z_2.shape}")
print("Samples for Z_2:")
print(Z_2[:5])

A_2 = Y_hat = sigmoid(Z_2 + c.T)
print(f"Shape of A_2 is {A_2.shape}")
print("Samples for A_2:")
print(A_2[:5])



Shape of W_0 is (2, 2)
[[-1.02508588  0.46696045]
 [ 2.21330278 -0.07245527]]
2
Shape of b_1 is (2, 1)

Shape of Z_1 is (10, 2)
Samples for Z_1:
[[-2.68345628  6.16826567]
 [-1.16983628  6.54968094]
 [-1.69017413  0.4676782 ]
 [ 2.7643912  -9.05676926]
 [ 0.60593503 -1.12114244]]
Shape of A_1 is (10, 2)
Samples for A_1:
[[2.16110876e-02 9.97786773e-01]
 [9.11991217e-02 9.98487539e-01]
 [5.62838072e-02 6.01207890e-01]
 [8.36873470e-01 1.10107098e-04]
 [3.72078702e-01 2.35354378e-01]]

Shape of Z_2 is (10, 1)
Samples for Z_2:
[[ 0.74960207]
 [ 0.67597969]
 [ 0.40555862]
 [-0.89183156]
 [-0.214305  ]]
Shape of A_2 is (10, 1)
Samples for A_2:
[[0.30655818]
 [0.29113414]
 [0.23861219]
 [0.07887776]
 [0.14428253]]


In [25]:
def forward_prop(
    X_raw: np.array,
    W_0: np.array,
    b: np.array,
    V_0: np.array,
    c: np.array,
) -> Tuple:
    """Performs the forward propagation of the given NN."""
    # Note the NN structure is passed in from outside.
    Z_1 = X_raw @ W_0.T
    A_1 = sigmoid(Z_1 + b.T)

    Z_2 = A_1 @ V_0.T
    A_2 = Y = sigmoid(Z_2 + c.T)

    return A_2, Z_2, A_1, Z_1

Y_hat, _, _, _ = forward_prop(X_raw=X_raw, W_0=W_0, b=b, V_0=V_0, c=c)

In [28]:
def derivatives_by_backprop(
    X_raw: np.array,
    Y: np.array,
    W_0: np.array,
    b: np.array,
    V_0: np.array,
    c: np.array,
) -> Tuple:
    """Calculates the derivatives of the parameters by backforward propagation.

    Here we assume it is a binary classification problem, with sigmoid activation functions.
    """
    # forward propagation
    dW_2, db_2, dW_1, db_1 = 0, 0, 0, 0
    Y_hat, Z_2, A_1, Z_1 = forward_prop(X_raw=X_raw, W_0=W_0, b=b, V_0=V_0, c=c)
    n = len(Y_hat)

    loss = -np.mean(np.multiply(Y, np.log(Y_hat)) + np.multiply(1 - Y, np.log(1 - Y_hat)))

    dZ_2 = Y_hat - Y
    dV_0 = dZ_2.T @ A_1 / n
    dc = np.mean(dZ_2.T, axis=1, keepdims=True)

    dZ_1 = np.multiply(dZ_2 @ V_0, np.multiply(A_1, 1 - A_1))
    dW_0 = (dZ_1.T @ X_raw) / n
    db = np.mean(dZ_1.T, axis=1, keepdims=True)

    return dW_0, db, dV_0, dc, loss

dW_0, db, dV_0, dc, loss = derivatives_by_backprop(X_raw=X_raw, Y=Y, W_0=W_0, b=b, V_0=V_0, c=c)

In [35]:
def gradient_descent(
    X_raw: np.array,
    Y: np.array,
    W_0_init: np.array,
    b_init: np.array,
    V_0_init: np.array,
    c_init: np.array,
    learning_rate: float = 0.01,
    epsilon: float = 1e-6,
    verbose: bool = False,
) -> Tuple:
    """Runs gradient descent to fit the NN via backprop."""
    W_0 = W_0_init
    b = b_init
    V_0 = V_0_init
    c = c_init
    losses = [float("inf"), ]
    roc_auc_scores = [0.5, ]

    diff_in_loss = float("inf")
    iteration = 0
    while abs(diff_in_loss) > epsilon:
        iteration += 1
        dW_0, db, dV_0, dc, loss = derivatives_by_backprop(
            X_raw=X_raw, Y=Y, W_0=W_0, b=b, V_0=V_0, c=c
        )

        W_0 -= learning_rate * dW_0
        b  -= learning_rate * db
        V_0 -= learning_rate * dV_0
        c  -= learning_rate * dc

        losses.append(loss)
        diff_in_loss = losses[-1] - losses[-2]

        Y_hat, _, _, _ = forward_prop(X_raw=X_raw, W_0=W_0, b=b, V_0=V_0, c=c)
        roc_auc = roc_auc_score(y_true=Y, y_score=Y_hat)
        roc_auc_scores.append(roc_auc)

        if verbose and iteration % 10 == 0:
            print(loss, roc_auc)
    return W_0, b, V_0, c, losses

In [37]:
# parameters for the first layer
np.random.seed(42)
W_0_init = np.random.normal(size=(2, X_raw.shape[1]))
b_init  = np.random.normal(size=(2, 1))

# parameters for the second layer
V_0_init = np.random.normal(size=(1, W_0.shape[1]))
c_init  = np.random.normal(size=(1, 1))

W_0, b, V_0, c, losses = gradient_descent(
    X_raw=X_raw,
    Y=Y,
    W_0_init=W_0_init,
    b_init =b_init,
    V_0_init=V_0_init,
    c_init =c_init,
    learning_rate=0.1,
    epsilon=1e-3,
    verbose=True,
)

0.7145045497210597 0.4800000000000001
0.6908318952620344 0.6399999999999999
